### ISSUE TITLE
누멍이 테스트 TODO

### ISSUE THREAD

**Issue by GHeeJeon** [my-ggott-games/merge-character-test-numong#1]
- [x] 구현은 북마크 해둔 사이트를 참고할 것
- [x] 캐릭터 선정
- [x] 캐릭터 분류 및 분석
- [x] QnA 구상
 >  캐릭터 선정/분류/분석 후 캐릭터 이미지 리소스 확보
 > 질문도, 답변도 짧은 한 문장씩 나오게끔 간단하게 작성할 것 (keep-all 에 의존 X, `</br>`을 활용할 것)
- [x] 각 캐릭터 설명
- [x] .gitignore 생성(WebStorm)
- [x] 메인 페이지 구상
- [x] 질문 페이지 구상
- [x] 결과 페이지 구상
